### ISSUE TITLE
Feature Request - Check For Dependencies At Configure Time

### ISSUE THREAD

**Issue by fundamental** [rock-hopper/shuriken#1]
Rather than just assuming that dependencies are installed, it would be nice if the system checked for them. Additionally such a configuration step could detect if the system shipped with 'qmake' or 'qmake-qt4'.

**Comment by rock-hopper** [comment]
OK, that seems like a good idea

**Comment by rock-hopper** [comment]
I've updated the build script to check for dependencies. I think qmake-qt4 is necessary as qmake could try to build using qt5 which I haven't added support for yet.
