### ISSUE TITLE
Feature request: Import file given at command line

### ISSUE THREAD

**Issue by RobSis** [rock-hopper/shuriken#13]
Hello, first of all - thank you so much for bringing this software back to life!

One thing that would really help me with my workflow is if the application could open also audio files from the command line arguments. (It already works for project files).

I tried to do it by myself, but I got lost in the juce code... 🤔 (i'm noob).

Would it be possible?

**Comment by rock-hopper** [comment]
Yes, I think that should be fairly straight-forward to implement. Glad you're finding Shuriken useful!

**Comment by rock-hopper** [comment]
OK, that's it done!

**Comment by RobSis** [comment]
Perfect! Works great.
Thanks a lot.
