### ISSUE TITLE
Debian repository not compatible with Debian 9

### ISSUE THREAD

**Issue by nodiscc** [rock-hopper/shuriken#14]
I have tried the Debian installation the method described at https://github.com/rock-hopper/shuriken/releases (either by downloading the .deb directly or by  adding the suse repository). 

The installation fails due to Debian 9 missing [libaubio4](https://packages.debian.org/search?keywords=libaubio4) which was present in Debian 8. In Debian 9 [libaubio5](https://packages.debian.org/search?keywords=libaubio5) is present

Would it be possible to build the deb package/suse repository against libaubio5/debian 9?

**Comment by rock-hopper** [comment]
No problem, I'll try and get it done at the weekend.

**Comment by rock-hopper** [comment]
OK, all done!

**Comment by nodiscc** [comment]
Thanks! Will test in the coming days :+1:

Edit: installs and works without problems on Debian 9
