### ISSUE TITLE
debian compatibility

### ISSUE THREAD

**Issue by teletrail** [rock-hopper/shuriken#15]
hi I really like your application. is it possible to make the package more debian friendly though? your ubuntu repo version depends on librubberband2v5, while debian standard is librubberband2.

also for some reason I can't build from source due to package conflicts in dependencies.

somehow I got it working on my laptop (also debian) but can't run it on my desktop!

**Comment by rock-hopper** [comment]
I'm sorry, I don't understand what you mean by "more debian friendly". 

Ubuntu 14.04 has librubberband2 while later versions of Ubuntu have librubberband2v5
https://packages.ubuntu.com/search?keywords=librubberband&searchon=names&suite=all&section=all

Debian has librubberband2 only
https://packages.debian.org/search?keywords=librubberband&searchon=names&suite=all&section=all

If you're building from source you need to have all the required dev packages installed. Shuriken's build script could be better but it should give you an idea as to what packages are missing.

**Comment by teletrail** [comment]
hi, thanks for the reply.

when I try to compile from source it asks for packages that break my system
to install, namely libjack0, so I'd like to install from .deb, but it
requires librubberband2v5, which is not present in debian repositories.

 is there a way to make it use librubberband2 instead?

**Comment by rock-hopper** [comment]
Ah, I see. As well as an Ubuntu repository there are also repos for Debian Wheezy, Jessie, and Stretch:

https://github.com/rock-hopper/shuriken/releases/latest
