### ISSUE TITLE
Place slice points on bars (from BPM)

### ISSUE THREAD

**Issue by nodiscc** [rock-hopper/shuriken#16]
I'm experimenting with Shuriken and it works really well so far, thanks!

One thing I miss is the ability to auto-place slice points on each bar.

For example I have loops that I know are 16 bars long, so I enter `Length: 16 bars`, click `[BPM] Calc` and the bar/measure ruler at the top updates and aligns correctly with my loop. Now I'd like to be able to place slice points on each bar (each slice will be 1 bar long) - without audio detection, just following the calculated or manually entered BPM. This way I don't have to correct the slice points positions at all.

Maybe you could add a button `Slice` next to `Calc` that would place the slice points according to the BPM? Or a new entry in the `Detect by:` dropdown - `Slice on bars`.

Another option would be to have new slice points added with `Insert` "snap" to the closest beat on the ruler (perhaps with a setting - disable snapping, snap to bar, snap to 1/2 bar, snap to 1/4, 1/8, 1/16 ...)

Let me know if you like the idea, thanks again

**Comment by rock-hopper** [comment]
Hi nodiscc

Yes, auto-aligning slice points to each bar or beat-of-the-bar would be a nice time-saver. You've given me some good options to think about too!

**Comment by rock-hopper** [comment]
"Snap Values" option is now added to the "Detect by" dropdown when Find Beats is selected
