### ISSUE TITLE
"Export As..." dialog issues

### ISSUE THREAD

**Issue by mxmilkiib** [rock-hopper/shuriken#20]
When the Export dialog window opens with Export as Audio Files, the two Numbering radio buttons are ungrayed. If I change Export to H2 Drumkit, SFZ or Akai, the Numbering radio buttons are grayed out. However, if I then change the MIDI File dropdown from Export to Don't Export, the Numbering radio buttons are ungrayed. They are also made available if I click on the MIDI File dropdown and 'change' it from Export to Export.

MIDI File dropdown "Export Only" is slightly confusing working, maybe "Export MIDI File Only"?

Also, when I change Export to Akai, the Type 0 and Type 1 radio buttons are grayed out, with Type 1 selected. Maybe this is intentional anyway if an Akai export should always give a Type 1 MIDI file.

It would be nice if the any text in File Name field were saved when changing Export type.

**Comment by mxmilkiib** [comment]
AAAAhh, apologies, I wasn't running git head....

I /can/ enter a filename and I can save an SFZ.

Some of the state issues remain, so I'll redo this issue in the next few days.

Edit: I've fixed the bug report.

**Comment by rock-hopper** [comment]
Thanks for taking the time to report these bugs, which have likely been around for some time. Akai MIDI files are Type 1 so the radio buttons are intentionally greyed-out in that case.
