### ISSUE TITLE
Ubuntu 18

### ISSUE THREAD

**Issue by meadowsp** [rock-hopper/shuriken#28]
Hi, Is there any chance of updating the repos to support Ubuntu 18? 

Thanks!

**Comment by DroWnThePoor** [comment]
@meadowsp I was going to ask the same thing, I've been trying to build it from source but I'm in dependency hell.
I notice this repo hasn't been updated for a year, so the project could be dead or just on pause.

**Comment by rock-hopper** [comment]
Packages are now available for Ubuntu 18.04 and 19.04 in the PPA. Sorry you had to wait so long!

**Comment by DroWnThePoor** [comment]
Haha, don't be.
I'm just glad you're making this.
