### ISSUE TITLE
compile on ubuntu. 

### ISSUE THREAD

**Issue by LightSun** [rock-hopper/shuriken#30]
I downloaded the release codes of 0.5.2.
When i run './build' ,  I found problem. Is this mean i need download the dependent  packages 
 and compile them? 
```java
Checking dependencies...
No package 'alsa' found
No package 'jack' found
No package 'liblo' found
No package 'Qt5OpenGL' found
No package 'Qt5Core' found
No package 'Qt5Gui' found
No package 'rubberband' found
No package 'samplerate' found
No package 'sndfile' found
No package 'x11' found

One or more packages needed to build Shuriken couldn't be found.

```

**Comment by trebmuh** [comment]
> When i run './build' , I found problem. Is this mean i need download the dependent packages and compile them?

No. That probably mean you need to find the -dev packages for those. Example for "alsa", this should be "libasound2-dev", for "x11" -> "libx11-dev",...etc

**Comment by rock-hopper** [comment]
Hi @LightSun 

As @trebmuh said, you should be able to find all the necessary "-dev" packages using your package manager.

However, I've just uploaded .deb packages for Ubuntu 18.04 and 19.04 to the PPA, so you don't need to compile Shuriken yourself unless you want to.

**Comment by LightSun** [comment]
ok, thanks. Can i compile this on android? I see it contains multi third libraries. @rock-hopper @trebmuh

**Comment by rock-hopper** [comment]
It might be possible but I don't know for sure. Both Qt and JUCE can run on Android but I don't know about the other dependencies.

**Comment by LightSun** [comment]
ok. thanks
