### ISSUE TITLE
ubuntu 19.10

### ISSUE THREAD

**Issue by nolac** [rock-hopper/shuriken#31]
hello is there a way compiling (or is there PPA) for ubuntu19.10 ???

**Comment by rock-hopper** [comment]
Hi, I might not get the chance until next weekend, but I'll get this packaged for 19.10.

**Comment by rock-hopper** [comment]
Shuriken is now packaged for 19.10

https://launchpad.net/~rock-hopper/+archive/ubuntu/audiotools
