### ISSUE TITLE
enable monophony

### ISSUE THREAD

**Issue by rhetr** [rock-hopper/shuriken#5]
it'd be good to have an option to make shuriken monophonic, i.e. when one sample is triggered all the other samples are silenced.

**Comment by rock-hopper** [comment]
Yes, this would be a nice feature

**Comment by simonvanderveldt** [comment]
That's what the audition button already seams to do when you mouse click, right?
It's just that the MIDI doesn't do so. Would it be easy to fix this?

**Comment by rock-hopper** [comment]
Yes, this should be fairly simple to fix. I just haven't had much time to work on Shuriken for a while.

**Comment by rock-hopper** [comment]
OK, I've added a button to toggle monophonic mode. This setting will be saved along with your project.

**Comment by simonvanderveldt** [comment]
> OK, I've added a button to toggle monophonic mode. This setting will be saved along with your project.

Ah, that's awesome!
I wanted to see if/how it works, so I just did a build from current master and for me MIDI in doesn't seem to work anymore. Is there any kind of way to verify MIDI is actually coming in?
(I'm using JACK MIDI and it's working fine with all my other audio software)

**Comment by rock-hopper** [comment]
This bug seems to have been in Shuriken for some time (at least v0.3.2) so thanks for reporting it! If you use a2jmidid (ALSA to JACK MIDI Daemon) then Shuriken's JACK MIDI input works fine, but it doesn't work if you have JACK configured to use the ALSA "seq" MIDI driver instead. As a work-around, go into the options menu and tick "jack_midi" in the MIDI inputs checklist. In Patchage, Catia, etc. you should now see a new JACK MIDI port for Shuriken which you can connect to.

**Comment by rock-hopper** [comment]
Hi @simonvanderveldt 

> MIDI in doesn't seem to work anymore. Is there any kind of way to verify MIDI is actually coming in?
> (I'm using JACK MIDI and it's working fine with all my other audio software)

I've updated the JUCE library to the latest stable version (4.3.0) and also re-worked my modifications to the library which add JACK MIDI capability. Hopefully Shuriken will work properly with JACK MIDI now!

**Comment by simonvanderveldt** [comment]
> I've updated the JUCE library to the latest stable version (4.3.0) and also re-worked my modifications to the library which add JACK MIDI capability. Hopefully Shuriken will work properly with JACK MIDI now!

Bit late, but just did a new compile from master and it is indeed working again :)
Thanks!
