### ISSUE TITLE
Cannot open files other than .wav?

### ISSUE THREAD

**Issue by mxmilkiib** [rock-hopper/shuriken#9]
I'm on Arch Linux. I've installed via [shuriken-git](https://aur.archlinux.org/packages/shuriken-git/) and I get an "File contains data in an unknown format". dialog box and this in the console when attempting to open an mp3.

> AUBIO ERROR: source_sndfile: Failed opening /home/milk/music/02 Floating in Windows '95.mp3: File contains data in an unknown format.
> AUBIO ERROR: source_wavread: could not find RIFF header in /home/milk/music/02 Floating in Windows '95.mp3
> AUBIO ERROR: source: failed creating aubio source with /home/milk/music/02 Floating in Windows '95.mp3 at samplerate 0 with hop_size 4096

**Comment by rock-hopper** [comment]
Hi  milkmiruku. Shuriken uses libsndfile and sndlib to load audio files so unfortunately mp3 is not currently supported. However, this may change in the future as I'd like to make use of libav which can load just about anything.

I'm curious as to why you're getting those aubio errors. Have you customised the code in any way?

**Comment by mxmilkiib** [comment]
Fair enough, thanks :) No, I haven't changed the code.

**Comment by mxmilkiib** [comment]
libsndfile "Add MP3 support" issue - https://github.com/erikd/libsndfile/issues/258
